export type ApiReferenceAuth = "open" | "key" | "hmac";

export interface ApiReferenceEndpoint {
  method: "GET" | "POST" | "PUT";
  path: string;
  auth: ApiReferenceAuth;
}

export const apiReferenceEndpoints: ApiReferenceEndpoint[] = [
  { method: "GET", path: "/health", auth: "open" },
  { method: "GET", path: "/api/health", auth: "open" },
  { method: "GET", path: "/ready", auth: "open" },
  { method: "GET", path: "/metrics", auth: "open" },
  { method: "POST", path: "/api/apple/batch", auth: "key" },
  { method: "GET", path: "/api/apple/status", auth: "key" },
  { method: "GET", path: "/api/insights/latest", auth: "key" },
  { method: "GET", path: "/api/insights/daily", auth: "key" },
  { method: "GET", path: "/api/insights/weekly", auth: "key" },
  { method: "GET", path: "/api/insights/anomalies", auth: "key" },
  { method: "GET", path: "/api/insights/trends", auth: "key" },
  { method: "GET", path: "/api/insights/runs", auth: "key" },
  { method: "POST", path: "/api/insights/trigger", auth: "key" },
  { method: "GET", path: "/api/v2/meta", auth: "open" },
  { method: "GET", path: "/api/v2/setup/diagnostics", auth: "open" },
  { method: "GET", path: "/api/v2/metrics", auth: "open" },
  { method: "GET", path: "/api/v2/metrics/vital.heart_rate/series", auth: "key" },
  { method: "GET", path: "/api/v2/series?ids=vital.heart_rate", auth: "key" },
  { method: "GET", path: "/api/v2/sources", auth: "key" },
  { method: "GET", path: "/api/v2/devices", auth: "key" },
  { method: "GET", path: "/api/v2/streams", auth: "key" },
  { method: "GET", path: "/api/v2/streams/00000000-0000-5000-8000-000000000000", auth: "key" },
  { method: "GET", path: "/api/v2/insights/latest", auth: "key" },
  { method: "GET", path: "/api/v2/insights/correlations", auth: "key" },
  { method: "GET", path: "/api/v2/insights/findings", auth: "key" },
  { method: "GET", path: "/api/v2/insights/narratives", auth: "key" },
  { method: "POST", path: "/api/v2/insights/trigger", auth: "key" },
  { method: "GET", path: "/api/v2/sync/runs/latest", auth: "key" },
  { method: "GET", path: "/api/v2/sync/runs/example", auth: "key" },
  { method: "GET", path: "/api/v2/sync/coverage", auth: "key" },
  { method: "GET", path: "/api/v2/sync/anomalies", auth: "key" },
  { method: "GET", path: "/api/v2/changes", auth: "key" },
  { method: "GET", path: "/api/v2/receipts", auth: "key" },
  { method: "GET", path: "/api/v2/experiments", auth: "key" },
  { method: "POST", path: "/api/v2/experiments", auth: "key" },
  { method: "GET", path: "/api/v2/experiments/candidates", auth: "key" },
  { method: "GET", path: "/api/v2/experiments/example", auth: "key" },
  { method: "POST", path: "/api/v2/experiments/example/analyze", auth: "key" },
  { method: "POST", path: "/api/v2/experiments/example/abandon", auth: "key" },
  { method: "GET", path: "/api/v2/agents/proposals", auth: "key" },
  { method: "POST", path: "/api/v2/agents/proposals/example/decide", auth: "key" },
  { method: "GET", path: "/api/v2/readiness", auth: "key" },
  { method: "GET", path: "/api/v2/privacy", auth: "key" },
  { method: "GET", path: "/api/v2/intelligence", auth: "key" },
  { method: "PUT", path: "/api/v2/intelligence", auth: "key" },
  { method: "POST", path: "/api/v2/intelligence/consent", auth: "key" },
  { method: "POST", path: "/api/v2/intelligence/test-connection", auth: "key" },
  { method: "GET", path: "/api/v2/intelligence/detect-local", auth: "key" },
  { method: "GET", path: "/api/v2/export/metrics", auth: "key" },
  { method: "GET", path: "/api/v2/export", auth: "key" },
  { method: "POST", path: "/api/v2/sources/whoop/webhook", auth: "hmac" },
];
